# local bin
export PATH=$HOME/bin:$PATH

# local::lib
eval $(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)

# Alias
if [ -f ~/.alias ]; then
    source ~/.alias
fi

# Local Alias
if [ -f ~/.alias_local ]; then
    source ~/.alias_local
fi

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

if [ -f /opt/local/etc/bash_completion ]; then
    . /opt/local/etc/bash_completion
fi
